PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ebucore: <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX myGazetteer: <http://maps.org/gazetteer/>
PREFIX pcdm: <http://pcdm.org/models#>
PREFIX schema: <http://schema.org/>
PREFIX testRepository: <http://institution.edu/repository/>
INSERT DATA
{
  myGazetteer:boundingBox1 a schema:GeoShape ;
    geo:asWKT "POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))"^^geo:wktLiteral ;
    schema:box "30,10 40,40" .

  myGazetteer:place1 a schema:Place ;
    schema:name "Example Place 1"@en ;
    schema:geo  myGazetteer:boundingBox1 .

  testRepository:exampleScannedMap a pcdm:Work, schema:Map ;
    dcterms:spatial    myGazetteer:place1 ;
    dcterms:description    "An Example Scanned Map"@en ;
    schema:spatialCoverage    myGazetteer:place1 ;
    ebucore:hasMimeType    "image/tiff" .
}
