PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX ogc: <http://www.opengis.net/ont/geosparql#>
PREFIX ogcf: <http://www.opengis.net/def/function/geosparql/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX schema: <http://schema.org/>
PREFIX sdmx-concept: <http://purl.org/linked-data/sdmx/2009/concept#>
PREFIX testRepository: <http://institution.edu/repository/>

SELECT ?resource ?sample ?rasterCell ?temperature
WHERE
{
  ?resource schema:spatialCoverage ?fPlace .
  ?fPlace schema:geo ?fGeom .
  ?fGeom ogc:asWKT ?polygon .
  ?area qb:concept sdmx-concept:refArea .
  ?areaDimension qb:dimension ?area .
  ?sample ?areaDimension ?rasterCell .
  ?sample testRepository:temperature ?temperature
  FILTER (ogcf:sfWithin(?polygon,"POLYGON ((0 0, 50 0, 50 50, 0 50, 0 0))"^^ogc:wktLiteral))
}
