PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX ogc: <http://www.opengis.net/ont/geosparql#>
PREFIX ogcf: <http://www.opengis.net/def/function/geosparql/>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX schema: <http://schema.org/>
PREFIX sdmx-concept: <http://purl.org/linked-data/sdmx/2009/concept#>
PREFIX testRepository: <http://institution.edu/repository/>

SELECT ?rasterCell ?hyraxes
WHERE
{
  ?resource schema:spatialCoverage ?fPlace .
  ?fPlace schema:geo ?fGeom .
  ?fGeom ogc:asWKT ?polygon .
  ?area qb:concept sdmx-concept:refArea .
  ?areaDimension qb:dimension ?area .
  ?sample ?areaDimension ?rasterCell .
  ?sample qb:measureType ?hyraxMeasure .
  ?sample ?hyraxMeasure ?hyraxes
  FILTER (ogcf:sfWithin(?polygon,"POLYGON ((30 5, 50 45, 15 45, 0 15, 30 5))"^^ogc:wktLiteral))
}
