PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX schema: <http://schema.org/>

SELECT ?resource ?polygon
WHERE
{
  ?resource schema:spatialCoverage ?fPlace .
  ?fPlace schema:geo ?fGeom .
  ?fGeom geo:asWKT ?polygon .
  FILTER (geof:sfWithin(?polygon,"POLYGON ((30 5, 50 45, 15 45, 0 15, 30 5))"^^geo:wktLiteral))
}
